// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ2mecKWVu_n-R8sQXdEBIyKLbY5zXAQQ',
    appId: '1:240456767739:web:159cca6a09d6abf252b85e',
    messagingSenderId: '240456767739',
    projectId: 'trading-jornal',
    authDomain: 'trading-jornal.firebaseapp.com',
    storageBucket: 'trading-jornal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlrc7QjqdKBiBadqEGnMPOUlA7XH_CzNg',
    appId: '1:240456767739:android:7e0d3155f2f90cc252b85e',
    messagingSenderId: '240456767739',
    projectId: 'trading-jornal',
    storageBucket: 'trading-jornal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsNBv-BK4jYAxNv6s60HDj0v8wVDLL4TQ',
    appId: '1:240456767739:ios:15ae61dbca94652152b85e',
    messagingSenderId: '240456767739',
    projectId: 'trading-jornal',
    storageBucket: 'trading-jornal.firebasestorage.app',
    iosBundleId: 'com.example.tj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsNBv-BK4jYAxNv6s60HDj0v8wVDLL4TQ',
    appId: '1:240456767739:ios:15ae61dbca94652152b85e',
    messagingSenderId: '240456767739',
    projectId: 'trading-jornal',
    storageBucket: 'trading-jornal.firebasestorage.app',
    iosBundleId: 'com.example.tj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ2mecKWVu_n-R8sQXdEBIyKLbY5zXAQQ',
    appId: '1:240456767739:web:4754f10cf96471b852b85e',
    messagingSenderId: '240456767739',
    projectId: 'trading-jornal',
    authDomain: 'trading-jornal.firebaseapp.com',
    storageBucket: 'trading-jornal.firebasestorage.app',
  );
}
